name: project22
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/bg/
    - assets/spinner/
    - assets/slot/
    - assets/images/
    - assets/slot3/
    - assets/slot2/
    - assets/slot1/
  fonts:
    - family: Alkatra
      fonts:
        - asset: assets/fonts/Alkatra-Regular.ttf